### PR TITLE
NO-REF: ConsistentResponseHandler should not wait forever

### PR DESCRIPTION
**Pull request by cluePrints**
Summary:

     Uninterruptibles.getUninterruptibly(future) --> Uninterruptibles.getUninterruptibly(future, timeout)

+ bunch of tests / refactorings to make that happen

### CODE REVIEW

**Comment by odiszapc** [comment]
Dear @cluePrints, thanks a lot for the merge request.

We use `SocketOpts#readTimeoutMs()` value as a "wait for response from Storage Node" timeout. It's a `io.netty.util.HashedWheelTimer` implementation. For any RF we guarantee that all responses  fit in `SocketOpts#readTimeoutMs()` window (with success or timeout) anyway and at a first glance we don't need another timeout.

Technically speaking we never reach timeout in `ConsistentResponseHandler`. But theoretically (code bugs) it's a possible situation.

You can  pass the `SocketOpts#readTimeoutMs()` to `ConsistentResponseHandler(...)` constructor and remove one you added in QueryOpts, its not clear when there are two configurable timeouts.

Another thought, we can RACE with two timeouts when they both have equal values, common one is a per connection (Netty) timeout. The timeout you implemented is a `technical` timeout. Just ensure that it's bigger than `SocketOpts#readTimeoutMs()` by multiplying it by 2, for example.

Another issue is the `long timeoutMs` not used in `ConsistentResponseHandler(..., long timeoutMs)`

Thanks.

**Comment by cluePrints** [comment]
@odiszapc updated

**Comment by odiszapc** [comment]
@cluePrints The `long timeoutMs` parameter is not used in `ConsistentResponseHandler(..., long timeoutMs)` constructor

Next, `shouldThrowOnWaitForIfConsistencyCanNotBeAchieved` test fails throwing an Exception:

    java.lang.Exception: test timed out after 100 milliseconds
    	at java.net.NetworkInterface.getMacAddr0(Native Method)
    	at java.net.NetworkInterface.getHardwareAddress(NetworkInterface.java:448)
    	at sun.security.provider.SeedGenerator.addNetworkAdapterInfo(SeedGenerator.java:229)
    	at sun.security.provider.SeedGenerator.access$000(SeedGenerator.java:77)
    	at sun.security.provider.SeedGenerator$1.run(SeedGenerator.java:177)
    	at sun.security.provider.SeedGenerator$1.run(SeedGenerator.java:162)
    	at java.security.AccessController.doPrivileged(Native Method)
    	at sun.security.provider.SeedGenerator.getSystemEntropy(SeedGenerator.java:161)
    	at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:184)
    	at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:203)
    	at java.security.SecureRandom.nextBytes(SecureRandom.java:455)
    	at java.util.UUID.randomUUID(UUID.java:145)
    	at org.stem.client.ConsistentResponseHandlerTest.createResultFuture(ConsistentResponseHandlerTest.java:107)
    	at org.stem.client.ConsistentResponseHandlerTest.shouldThrowOnWaitForIfConsistencyCanNotBeAchieved(ConsistentResponseHandlerTest.java:62)

**Comment by odiszapc** [comment]
Maybe `shouldThrowOnWaitForIfConsistencyCanNotBeAchieved` should have annotations claiming that test must throw an Exception

**Comment by cluePrints** [comment]
timeoutMs - done, was cherrypicking stuff as my Eclipse format-on-save is mad
shouldThrowOnWaitForIfConsistencyCanNotBeAchieved  -->  `this.expectedException.expectMessage("Response is inconsistent");` or that's not enough?

**Comment by odiszapc** [comment]
Doesn't work:

    java.lang.AssertionError: 
    Expected: exception with message a string containing "Response is inconsistent"
         but: message was "test timed out after 100 milliseconds"
    Stacktrace was: java.lang.Exception: test timed out after 100 milliseconds

Timeout? Looks like your Netty timouter resolution of 100ms too rough for

    @Test(timeout = 100)

**Comment by cluePrints** [comment]
Super weird, I'm not even expecting netty to kick in :) When we'll raise a series A, we'll buy you a faster macbook :P

Updated.

**Comment by odiszapc** [comment]
@cluePrints Well done!

**Pull request merged**
